services:
  app:
    image: ${APP_NAME}
    container_name: ${APP_NAME}-app
    build:
      context: ..
      dockerfile: api-gateway/Dockerfile.dev
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - ./.env
    environment:
      - NATS_URL=${NATS_URL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - tourgis-network

  redis:
    image: redis:7-alpine
    container_name: ${APP_NAME}-redis
    ports:
      - '${REDIS_PORT:-6380}:6379'
    volumes:
      - redis_data:/data
    networks:
      - tourgis-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:

networks:
  tourgis-network:
    name: tourgis-network
    driver: bridge
    external: false
